MicroShop/MicroShop.Web/Models/DTOs/ProductDTO.cs
namespace MicroShop.Web.Models.DTOs
{
    public class ProductDTO
    {
        public string? Id { get; set; }
        public string? Name { get; set; }
        public decimal? Price { get; set; }
        public int? Stock { get; set; }
    }
}

MicroShop/MicroShop.Web/Models/ErrorViewModel.cs
namespace MicroShop.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MicroShop/MicroShop.Web/Controllers/CartsController.cs
using MicroShop.Web.Application.Interface;
using MicroShop.Web.Domain.DTOs.CartDTOs;
using MicroShop.Web.Utils;
using Microsoft.AspNetCore.Mvc;

namespace MicroShop.Web.Controllers
{
    public class CartsController : Controller
    {
        private readonly ICartService _cartService;
        public CartsController(ICartService cartService)
        {
            _cartService = cartService;
        }

        [HttpPost]
        public async Task<IActionResult> AddProductToCart(string productId)
        {
            var userId = GetUserIdFromJWT.GetUserIdFromToken(Request.Cookies["jwt"]);

            var result = await _cartService.AddProductToCart(new AddProductToCartDTO { ProductId = productId, UserId = userId});

            if (result)
            {
                TempData["UserMessage"] = "Product added in cart.";
                TempData["MessageType"] = "success";
            }
            else
            {
                TempData["UserMessage"] = "Product removed from cart.";
                TempData["MessageType"] = "error";
            }

            return RedirectToAction("Index", "Products");
        }
    }
}

MicroShop/MicroShop.Web/Controllers/HomeController.cs
using MicroShop.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MicroShop.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MicroShop/MicroShop.Web/Controllers/ProductsController.cs
using MicroShop.Web.Application.Interface;
using MicroShop.Web.Domain.DTOs.CartDTOs;
using MicroShop.Web.Domain.DTOs.ProductDTOs;
using MicroShop.Web.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace MicroShop.Web.Controllers
{
    public class ProductsController : Controller
    {
        private readonly HttpClient _productApiClient;
        private readonly HttpClient _cartApiClient;

        private readonly IProductService _productService;
        public ProductsController(IHttpClientFactory httpClientFactory, IProductService productService , IHttpClientFactory cartApiClient)
        {
            _productApiClient = httpClientFactory.CreateClient("ProductAPI");
            _cartApiClient = httpClientFactory.CreateClient("CartAPI");
            _productService = productService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = GetUserIdFromJWT.GetUserIdFromToken(Request.Cookies["jwt"]);
            HttpResponseMessage response = await _productApiClient.GetAsync("api/products");

            if (response.IsSuccessStatusCode)
            {
                List<ProductDTO> products = await response.Content.ReadFromJsonAsync<List<ProductDTO>>();

                HttpResponseMessage cartResponse = await _cartApiClient.GetAsync($"api/v1/carts/{userId}/cartItems");

                if (cartResponse.IsSuccessStatusCode)
                {
                    List<CartItemDTO> cartItems = await cartResponse.Content.ReadFromJsonAsync<List<CartItemDTO>>();

                    foreach (var product in products)
                    {
                        product.IsInCart = cartItems.Any(ci => ci.ProductId == product.Id);
                    }
                }
                return View(products);
            }
            return View("Error");
        }

        [Authorize]
        [HttpGet]
        public IActionResult ProductCreatePage()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> ProductCreate(ProductDTO productDto)
        {
            if (ModelState.IsValid)
            {
                await _productService.CreateProduct(productDto);
                return RedirectToAction("Index");
            }
            return View(productDto);
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> ProductUpdatePage(string id)
        {
            var product = await _productService.GetProductById(id);
            return View(product);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> ProductUpdate(ProductDTO productDto)
        {
            if (ModelState.IsValid)
            {
                var response = await _productService.UpdateProduct(productDto);
                if (response != null) return RedirectToAction(
                    nameof(Index));
            }
            return View(productDto);
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> ProductDeletePage(string id)
        {
            var product = await _productService.GetProductById(id);
            return View(product);

        }
        [Authorize]
        [HttpPost]
        public async Task<ActionResult> ProductDelete(string id)
        {
            var response = await _productService.DeleteProductAsync(id);
            if (response) return RedirectToAction(nameof(Index));
            return View(response);
        }
    }
}

MicroShop/MicroShop.Web/Controllers/UsersController.cs
using MicroShop.Web.Application;
using MicroShop.Web.Domain.DTOs.UserDTOs;
using MicroShop.Web.Domain.Entities;
using MicroShop.Web.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace MicroShop.Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService _userService;
        public UsersController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult RegisterPage()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserRegisterDTO registerDto)
        {
            if (!ModelState.IsValid)
            {
                return View(registerDto);
            }
            var result = await _userService.RegisterUserAsync(registerDto);
            if (result == null)
            {
                ModelState.AddModelError("", "Failed to register user.");
                return View(registerDto);
            }
            return RedirectToAction("LoginPage");
        }
        public IActionResult LoginPage()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(UserLoginDTO loginDto)
        {
            if (!ModelState.IsValid) return View(loginDto);
            var token = await _userService.AuthenticateAsync(loginDto);
            if (token == null)
            {
                ModelState.AddModelError("", "Invalid username or password.");
                return View(loginDto);
            }
            Response.Cookies.Append("jwt", token, new CookieOptions
            {
                HttpOnly = true,
                Secure = true,
            });
            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public IActionResult Logout()
        {
            Response.Cookies.Delete("jwt");
            return RedirectToAction("Index", "Home");
        }
        [Authorize]
        [HttpGet]
        public async Task<ActionResult<User>> UserEditPage()
        {
            return View(await _userService.GetUserById(GetUserIdFromJWT.GetUserIdFromToken(Request.Cookies["jwt"])));
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> UserEdit(User user)
        {
            var updatedUser = await _userService.UpdateUserAsync(user);
            if (updatedUser != null)
            {
                return RedirectToAction("UserEditPage", "Users");
            }
            return View(user);
        }
    }
}

MicroShop/MicroShop.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MicroShop/MicroShop.Web/Views/Products/Index.cshtml
@using MicroShop.Web.Domain.DTOs.ProductDTOs
@model List<ProductDTO>

@{
    var userMessage = TempData["UserMessage"] as string;
    var messageType = TempData["MessageType"] as string;
    var alertClass = messageType == "success" ? "alert-success" : "alert-danger";
}

@if (!string.IsNullOrEmpty(userMessage))
{
    <div class="alert @alertClass">
        @userMessage
    </div>
}

<h1>Product List</h1>

<a asp-action="ProductCreatePage" class="btn btn-primary mb-3">Create Product</a>

@if (Model != null && Model.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Price</th>
                <th>Stock</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model)
            {
                var buttonText = product.IsInCart ? "Remove from Cart" : "Add to Cart";
                var buttonClass = product.IsInCart ? "btn-danger" : "btn-success";
                <tr>
                    <td>@product.Id</td>
                    <td>@product.Name</td>
                    <td>@product.Price</td>
                    <td>@product.Stock</td>
                    <td>
                        <a asp-action="ProductUpdatePage" class="btn btn-success" asp-route-id="@product.Id">
                            <i class="fas fa-edit">Edit</i>
                        </a>
                        <a asp-action="ProductDeletePage" class="btn btn-danger" asp-route-id="@product.Id">
                            <i class="fas fa-trash">Delete</i>
                        </a>
                        <form asp-action="AddProductToCart" asp-controller="Carts" method="post">
                            <input type="hidden" name="productId" value="@product.Id" />
                            <button type="submit" class="btn @buttonClass">
                                <i class="fas fa-edit"></i> @buttonText
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No products found.</p>
}

MicroShop/MicroShop.Web/Views/Products/ProductCreatePage.cshtml
@using MicroShop.Web.Domain.DTOs.ProductDTOs
@model ProductDTO

<form asp-action="ProductCreate">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create Product</h1>

        <hr />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size=20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
            <div class="col-2">
                <label asp-for="Price" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="Stock" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="col-5 offset-2">
                <a asp-action="ProductIndex" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial">
}

MicroShop/MicroShop.Web/Views/Products/ProductDeletePage.cshtml
@using MicroShop.Web.Domain.DTOs.ProductDTOs
@model ProductDTO
<form asp-action="ProductDelete">
    <input asp-for="Id" hidden>
    <br/>
    <div class="container border p-3">
        <hr/>
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size=20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" disabled class="form-control"/>
            </div>
            <div class="col-2">
                <label asp-for="Price" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Price" disabled class="form-control" />
            </div>
            <div class="col-2">
                <label asp-for="Stock" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Stock" disabled class="form-control" />
            </div>
            <div class="col-5 offset-2">
                <a asp-action="Index" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-danger form-control" />
            </div>
        </div>
    </div>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial">
}

MicroShop/MicroShop.Web/Views/Products/ProductUpdatePage.cshtml
@using MicroShop.Web.Domain.DTOs.ProductDTOs
@model ProductDTO

<form asp-action="ProductUpdate">
    <input asp-for="Id" hidden>
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Update Product</h1>
        <hr/>
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-2">
                <label asp-for="Name" class="control-label pt-2" style="font-size=20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
            <div class="col-2">
                <label asp-for="Price" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="Stock" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Stock" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="col-5 offset-2">
                <a asp-action="Index" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Update" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial">
}

MicroShop/MicroShop.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MicroShop.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MicroShop.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MicroShop.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="RegisterPage">Register</a>
                        </li>
                        @if (HttpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="UserEditPage">Configurações de Usuário</a>
                            </li>
                            <li class="nav-item">
                                <form asp-area="" asp-controller="Users" asp-action="Logout" method="post" style="display:inline;">
                                    <button type="submit" class="btn btn-link nav-link text-dark" style="padding: 0; border: none; background: none;">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="LoginPage">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MicroShop.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MicroShop/MicroShop.Web/Views/Users/LoginPage.cshtml
@using MicroShop.Web.Domain.DTOs.UserDTOs
@model UserLoginDTO

<h1>Login</h1>
<form asp-action="Login" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div>
        <label asp-for="Username">Username:</label>
        <input asp-for="Username" class="form-control" />
        <span asp-validation-for="Username" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="Password">Password:</label>
        <input asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <input type="submit" value="Login" class="btn btn-success" />
</form>

MicroShop/MicroShop.Web/Views/Users/RegisterPage.cshtml
@using MicroShop.Web.Domain.DTOs.UserDTOs

@model UserRegisterDTO

@{
    ViewData["Title"] = "Register";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Register" method="post" class="form-horizontal">
    <div class="form-group">
        <label asp-for="Username" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Username" class="form-control" />
            <span asp-validation-for="Username" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="FirstName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Password" class="form-control" type="password" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Register</button>
        </div>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MicroShop/MicroShop.Web/Views/Users/UserEditPage.cshtml
@using MicroShop.Web.Domain.Entities
@model User

@{
    ViewData["Title"] = "Edit User Information";
}

<h1>Edit User Information</h1>

<form asp-action="UserEdit" method="post">
    <input asp-for="Id" type="hidden" />
    <div class="form-group">
        <label asp-for="Username" class="control-label"></label>
        <input asp-for="Username" class="form-control" />
        <span asp-validation-for="Username" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="FirstName" class="control-label"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="control-label"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="control-label"></label>
        <input asp-for="Password" class="form-control" type="password" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Role" class="control-label"></label>
        <input asp-for="Role" class="form-control" />
        <span asp-validation-for="Role" class="text-danger"></span>
    </div>
    <div class="form-group">
        <div class="form-check">
            <input asp-for="IsEmailConfirmed" class="form-check-input" />
            <label asp-for="IsEmailConfirmed" class="form-check-label"></label>
        </div>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Save Changes</button>
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}